### ISSUE TITLE
About the driver

### ISSUE THREAD

**Issue by Jianglf19** [relativty/Relativty#71]
Turn on steamvr, no matter whether my gyroscope is moving or not, the screen will jitter violently. I thought the gyroscope was broken, but the data on the serial port monitoring tool is normal
From Google Translate

**Comment by okawo80085** [comment]
what sensor are you using?

**Comment by Jianglf19** [comment]
Is gy9250(mpu9250 chip)+arduino due

**Comment by Jianglf19** [comment]
> 您正在使用什么传感器？
> 
> 您正在使用什么arduino固件？

Is gy_9250(mpu9250 chip) and arduino due

**Comment by okawo80085** [comment]
im guessing you used arduino code from `Relativty/Relativty_Firmware/MP9250-HID/MP9250-HID.ino`

if you're using that arduino code, you *have* to change this to `false` in the driver config
```json
...
"hmdIMUdmpPackets":  false,
...
```

**Comment by Jianglf19** [comment]
> 我猜你使用了arduino代码 `Relativty/Relativty_Firmware/MP9250-HID/MP9250-HID.ino`
> 
> 如果您使用的是arduino代码，则_必须_`false`在驱动程序配置中将其更改为
> 
> ```json
> ...
>  “ hmdIMUdmpPackets ”：   false，
> ...
> ```

Thank you for your help, it can be used normally
